// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kocipwxrlvyeqlzlqyor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvY2lwd3hybHZ5ZXFsemxxeW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjYxMDAsImV4cCI6MjA2MjAwMjEwMH0.zjqbvHyR3NYmCTNolAaD3LfPL9RGdwHzDvckVItKkDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);